version: "3"

networks:
  server:
    driver: bridge

services:
  reverse-proxy-container:
    image: 429176748143.dkr.ecr.ap-northeast-2.amazonaws.com/reverse-proxy:latest
    platform: linux/amd64
    build:
      context: ./nginx
    ports:
      - 80:80
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logrotate.conf:/etc/logrotate.conf
    environment:
      TZ: Asia/Seoul
    links:
      - emerdy-app-container
    depends_on:
      - emerdy-app-container
    networks:
      - server

  emerdy-app-container:
    image: 429176748143.dkr.ecr.ap-northeast-2.amazonaws.com/emerdy-app:latest
    platform: linux/amd64
    build:
      context: ./server
    ports:
      - 3000:3000
      - 3030:3030
    environment:
      TZ: Asia/Seoul
    env_file:
      - ./server/.env
    networks:
      - server
